/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsM2mRouteImport } from './routes/projects/m2m'
import { Route as ProjectsDeskmateRouteImport } from './routes/projects/deskmate'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsM2mRoute = ProjectsM2mRouteImport.update({
  id: '/projects/m2m',
  path: '/projects/m2m',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDeskmateRoute = ProjectsDeskmateRouteImport.update({
  id: '/projects/deskmate',
  path: '/projects/deskmate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/resume': typeof ResumeRoute
  '/projects/deskmate': typeof ProjectsDeskmateRoute
  '/projects/m2m': typeof ProjectsM2mRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/resume': typeof ResumeRoute
  '/projects/deskmate': typeof ProjectsDeskmateRoute
  '/projects/m2m': typeof ProjectsM2mRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/resume': typeof ResumeRoute
  '/projects/deskmate': typeof ProjectsDeskmateRoute
  '/projects/m2m': typeof ProjectsM2mRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/resume'
    | '/projects/deskmate'
    | '/projects/m2m'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/resume'
    | '/projects/deskmate'
    | '/projects/m2m'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/resume'
    | '/projects/deskmate'
    | '/projects/m2m'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  ResumeRoute: typeof ResumeRoute
  ProjectsDeskmateRoute: typeof ProjectsDeskmateRoute
  ProjectsM2mRoute: typeof ProjectsM2mRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/m2m': {
      id: '/projects/m2m'
      path: '/projects/m2m'
      fullPath: '/projects/m2m'
      preLoaderRoute: typeof ProjectsM2mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/deskmate': {
      id: '/projects/deskmate'
      path: '/projects/deskmate'
      fullPath: '/projects/deskmate'
      preLoaderRoute: typeof ProjectsDeskmateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  ResumeRoute: ResumeRoute,
  ProjectsDeskmateRoute: ProjectsDeskmateRoute,
  ProjectsM2mRoute: ProjectsM2mRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
